version: '3.8'
services:
  frontend:
    build:
      context: ./v3-ui
    container_name: frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: ./v3-api
    container_name: backend
    ports:
      - "5001:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - frontend
      - backend