version: '3.8'
services:
  frontend:
    build:
      context: ./v3-ui
    container_name: frontend
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    networks:
      - backend

  backend:
    build:
      context: ./v3-api
    container_name: backend
    networks:
      - backend
networks:
  backend: